### BIOSTAT 615 PROJECT: GLM for 4-d TASK fMRI

## Preparation

# Inputs: 
# image_files: A list of file paths to 3D images, each representing an observation (y_i, i = 1,...,n).
# design_mat: Path to a text file containing the design matrix (X).
# contrast_vec: Path to a text file containing the contrast vector.

# Outputs:
# beta_images: A set of 3D images representing the β coefficients for each factor in X.
# contrast_image: A 3D image representing the weighted sum of β images according to the contrast vector.

# Pseudocode for glm function

glm_voxelwise <- function(image_files, design_mat, contrast_vec) {
  # Step 1: Load the design matrix and contrast vector
  X <- read_matrix(design_mat)
  contrast <- read_vector(contrast_vec)
  
  # Step 2: Load images into a 4D array
  # Assuming the images have the same dimensions: (x, y, z)
  Y <- load_images_4d_array(image_files) # Shape: (x, y, z, n)
  
  # Step 3: Dimensions of input data
  x_dim <- dim(Y)$x
  y_dim <- dim(Y)$y
  z_dim <- dim(Y)$z
  n <- dim(Y)$n
  k <- ncol(X) # number of columns in X (number of factors)
  
  # Step 4: Create an empty 4D array for β coefficient images
  beta_images <- array(0, dim = c(x_dim, y_dim, z_dim, k)) # Shape: (k, x, y, z)
  
  # The following steps are generated by chatGPT
  # Step 5: Loop over each voxel position (i, j, l)
  for i in range(x_dim):
    for j in range(y_dim):
      for l in range(z_dim):
    
        # Step 5a: Extract voxel values across images for current voxel position
        voxel_values <- Y[i, j, l, ] # Shape: (n,)
  
        # Step 5b: Solve for β coefficients at this voxel position
        if valid(voxel_values): # Check for non-missing, non-NaN values
          # GLM calculation: β = (X^T * X)^-1 * X^T * Y_voxel
          beta <- solve(t(design_matrix) %*% design_matrix) %*% t(design_matrix) %*% voxel_values
          # Store each β coefficient in the created beta_images array
          for factor in range(k):
            beta_images[i, j, l, factor] <- beta[factor]
  
  # Step 6: Apply the contrast vector to compute the contrast image
  contrast_image <- array(0, dim = c(x_dim, y_dim, z_dim)) # Shape: (x, y, z)
  for factor in range(k):
    contrast_image <- contrast_image + contrast_vector[factor] * beta_images[..., factor]
  
  # Step 7: Return the list of β coefficient images and the contrast image
  return(beta_images, contrast_image)
}
